# Generated by Django 5.2.7 on 2025-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devloom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Relative static path, e.g. devloom/images/laptop1.jpg', max_length=255, null=True),
        ),
    ]
